language: node_js
node_js:
  - "7"
  - "6"
  - "6.3"
os:
  - linux
 # - osx
env:
  global:
    - secure: L2jRZM+gmEOLTh2NMycmOmWuSwTKEeOXCA/XuoC1aTYewGB023Oa4M3DWTzpEAD6zWPARIBg2ilPME3N21XLa6wVg94dVcs44s9GVYJGenaSuuUPtMWRe1uQ8ltdu9C3OH+Z/S1nIwlINoAXOOK1+x4xJSPawO+WSHMjrXRq6O3yKJxkQwzo3zmH1PcnxX1NZgDwwgDJ3EoDLNrvAhAgu3TFJAPnY5d7babHt6IF0t9HS7sAD/x4ICbU0gWxuVTnDx38e6X60Al4md6bt3c0oJGwQMOn/q+Wkq/xXcakqvQCHxC34sSWkm/bv9u+t0msMUc0uuvA6s5kTRnhCEN5rQcEuH9rukPfZP5R3Uhl+pY77G3/BfTltovekxcms0mN3v2V0lLPAZfW81gfpGO0kIkk3pLlXzhh+7mJISduR07yj28ejM3MvMX5UovHnEcstcDrtcgqyzSJ7a3Ps2lkauUdVPB8QkM/aaY2iaMRp+z5aaOtN2+Srgr+bf5SIJndJ8WpXVs4rijq/JA5prPUKA2SJRKRKQNRNVH9/i/ft/F97mNGCpzzOt33lXCPRgYeU8czz0EIRLwsc29NY3FqfLHy4jp8W7azQoQH/TMKUhE3RQgWBWvunVRxrFfnNlEwGr8XHhjNqWegm/7xGP8T63iVDq/FxGDsn1Ps9KXXuXU= # CODECLIMATE
    - secure: PjeDcUrcuQBuuy8CimiKNrQ8WHtmXL0djG5o7Y6drBRKi8lq5Loe9ZYEikM6VJlo7s7yZ5l7trF4yGrgzsur4OH6o7MjnOeMiaQA4hjYTDrnbo/fYKc/r1n387Y3+7Fbx54LHW55bMtnlXaxeH5yMRRUud3SRml4V0KQgSkHXAOGQR0m3/HSL/QAIe4YreaqwdHkuTbRwYIbvLsxHxyk9M+gWWcf8fBagrLhZQqRS5l+X0vvWKB4LgM5V4CeBbV/XmxG8Su0nk3GJ6EIJiiABq4oE+kfHoUL86vNbOE6QG5GXZAsZ8xp/XcQAgrDyOMrI+qs9F+S9RYYsxiQwAgho39qYcMtUp42rnh7eM4/XJ2lJZc5uY37fQjxetEYDjFR7AWKQr1RtuzvnwH+Jxox9CgmFxM6a7IVad5z2RpDk8vJ9Pg4f7ijU53tYknAW47GPPoxaerzDa+AcH2w11bGg35JLw5Sd3R6q/H9TQto0YnYwHlEOBMzmuJ2xlXi+ti39t09m6g9EWYmVAPgmUoJirR6plkypvVdEEeoCZjZudBypniSvXSYV40FGMGsFP9MrD2aCZMDPBIMaIjL5XiF8Jguf5FDG9sID02DXjav31BOXkRpPnzUlB2/4CWOGJERsc5kgDV7KSk7QDKaV5YvBRp0Ht2WsebRo3CClCobfZU= # COVERALLS
before_install:
  - bash travisci/before_install.sh
sudo: required
addons:
  firefox: latest
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  #- bash travisci/before_script.sh
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - bash travisci/travis_script.sh
after_success:
  - bash travisci/after_success.sh
branches:
  only: master
cache:
  apt: true
  bundler: true
  directories:
    - node_modules